export const ROUTER_CATALOG = {
  intents: [
    { id: 'compare', keywords: ['비교', 'vs', '함께', '차이', '대비'] },
    { id: 'trend', keywords: ['추이', '흐름', '변화', '움직임'] },
    { id: 'rank', keywords: ['순위', '상위', '하위', 'top'] },
    { id: 'download', keywords: ['다운로드', '엑셀', 'csv', '내려받기'] },
  ],
  periodHints: [
    { label: '최근 1년', keywords: ['최근 1년', '1년'] },
    { label: '최근 3년', keywords: ['최근 3년', '3년'] },
    { label: '월간', keywords: ['월간', '월별', 'monthly'] },
    { label: '일간', keywords: ['일간', '일별', 'daily'] },
    { label: '분기', keywords: ['분기', 'quarter'] },
  ],
  concepts: [
    {
      id: 'fisis-bank-interest-income',
      source: 'FISIS',
      dataset: 'financial-company-metrics',
      label: '은행 이자수익',
      frequency: 'Q',
      synonyms: ['은행 이자수익', '국내 은행 이자수익', '은행 수익성', 'interest income'],
      description: '국내 은행권의 이자수익 또는 수익성 관련 지표 후보다.',
    },
    {
      id: 'fisis-capital-adequacy',
      source: 'FISIS',
      dataset: 'management-indicators',
      label: '자본적정성',
      frequency: 'Q',
      synonyms: ['bis', '자본적정성', '자기자본비율'],
      description: '은행 및 금융회사 건전성 지표를 찾는 데 사용한다.',
    },
    {
      id: 'ecos-base-rate',
      source: 'ECOS',
      dataset: 'macro-statistics',
      label: '한국은행 기준금리',
      frequency: 'M',
      synonyms: ['기준금리', '한국은행 기준금리', 'base rate'],
      description: '정책금리 추이를 조회할 때 사용한다.',
    },
    {
      id: 'ecos-cpi',
      source: 'ECOS',
      dataset: 'prices',
      label: '소비자물가지수',
      frequency: 'M',
      synonyms: ['cpi', '소비자물가', '물가', '인플레이션'],
      description: '물가 추세 비교용 지표다.',
    },
    {
      id: 'ecos-exchange-rate',
      source: 'ECOS',
      dataset: 'rates',
      label: '원달러 환율',
      frequency: 'D',
      synonyms: ['환율', '원달러', 'usdkrw', 'exchange rate'],
      description: '환율 시계열 비교용 지표다.',
    },
    {
      id: 'kofia-corporate-bond-yield',
      source: 'KOFIA',
      dataset: 'bond',
      label: '회사채 수익률',
      frequency: 'D',
      synonyms: ['회사채', '회사채 금리', '회사채 수익률', 'credit spread'],
      description: '채권 금리 및 스프레드 비교용 지표다.',
    },
    {
      id: 'kofia-fund-flow',
      source: 'KOFIA',
      dataset: 'fund',
      label: '펀드 자금 유출입',
      frequency: 'D',
      synonyms: ['펀드', '펀드 자금', 'fund flow'],
      description: '펀드 자금 흐름을 조회할 때 사용한다.',
    },
    {
      id: 'krx-kospi',
      source: 'KRX',
      dataset: 'index',
      label: 'KOSPI 지수',
      frequency: 'D',
      synonyms: ['kospi', '코스피', '코스피지수'],
      description: '대표 주가지수 추세 비교용 지표다.',
    },
    {
      id: 'krx-kosdaq',
      source: 'KRX',
      dataset: 'index',
      label: 'KOSDAQ 지수',
      frequency: 'D',
      synonyms: ['kosdaq', '코스닥', '코스닥지수'],
      description: '성장주 중심 지수 추세 비교용 지표다.',
    },
    {
      id: 'krx-trading-value',
      source: 'KRX',
      dataset: 'trading-value',
      label: '시장 거래대금',
      frequency: 'D',
      synonyms: ['거래대금', '주식 거래대금', 'market turnover'],
      description: '시장 유동성 비교용 지표다.',
    },
    {
      id: 'incos-loss-ratio',
      source: 'INCOS',
      dataset: 'incos-industry-core',
      label: '손해율',
      frequency: 'M',
      synonyms: ['손해율', '보험 손해율', 'loss ratio'],
      description: '보험업권과 보험사 수익성 해석용 지표다.',
    },
    {
      id: 'incos-gross-written',
      source: 'INCOS',
      dataset: 'incos-industry-core',
      label: '원수보험료',
      frequency: 'M',
      synonyms: ['원수보험료', '보험료', 'gross written premium'],
      description: '보험료 규모와 성장성 비교용 지표다.',
    },
    {
      id: 'incos-channel-share',
      source: 'INCOS',
      dataset: 'incos-channel-core',
      label: '채널 점유율',
      frequency: 'M',
      synonyms: ['채널 점유율', '전속', 'ga', '방카슈랑스', '온라인'],
      description: '보험 모집채널 믹스 변화를 해석하는 데 사용한다.',
    },
  ],
  sampleQueries: [
    '국내 은행 이자수익과 KOSPI 지수 추이 비교해줘',
    '한국은행 기준금리와 회사채 수익률 흐름을 보여줘',
    '보험 손해율과 모집채널 점유율 변화를 비교해줘',
  ],
};
